# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=50)),
                ('patro_incentivo', models.BooleanField(default=False)),
                ('patro_recibe', models.CharField(blank=True, max_length=50, null=True)),
                ('cada_cuando', models.CharField(blank=True, max_length=50, null=True)),
                ('donde_funciona', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('ocupacion', models.CharField(max_length=70)),
                ('lugar_trabajo', models.CharField(max_length=70)),
                ('formacion_academica', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_llenado', models.DateField(blank=True, null=True)),
                ('tiempo_facilitador', models.DateField(blank=True, null=True)),
                ('becado', models.BooleanField(default=False)),
                ('estudia', models.BooleanField(default=False)),
                ('donde_estudia', models.CharField(blank=True, max_length=70, null=True)),
                ('que_estudia', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEtnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_etnico', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('primer_periodo', models.BooleanField(default=False)),
                ('segundo_periodo', models.BooleanField(default=False)),
                ('horario', models.CharField(blank=True, max_length=80, null=True)),
                ('inicio_clases', models.DateTimeField()),
                ('fin_clases', models.DateTimeField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Centro')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Depto')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patrocinador', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('trabaja', models.BooleanField(default=False)),
                ('ocupacion', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grupo_etnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.GrupoEtnico')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_centro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoResidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Sexo'),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.TipoPersona'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Personas'),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Municipio'),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Sexo'),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='tipo_residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.TipoResidencia'),
        ),
        migrations.AddField(
            model_name='depto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Pais'),
        ),
        migrations.AddField(
            model_name='centro',
            name='patrocinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Patrocinador'),
        ),
        migrations.AddField(
            model_name='centro',
            name='promotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Personas'),
        ),
        migrations.AddField(
            model_name='centro',
            name='tipo_centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.TipoCentro'),
        ),
        migrations.AddField(
            model_name='centro',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Zona'),
        ),
    ]
