# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitador',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='formacion_academica',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
