# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20171002_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='centro',
            name='patro_incentivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recibe_Incentivo', to='adminapp.Descicion'),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='becado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becado', to='adminapp.Descicion'),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='estudia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudia', to='adminapp.Descicion'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='primer_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Primer_Periodo', to='adminapp.Descicion'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='segundo_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Segundo_Periodo', to='adminapp.Descicion'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='trabaja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabaja', to='adminapp.Descicion'),
        ),
    ]
