# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20171006_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fin_clases',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='inicio_clases',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
