# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20171009_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='facilitador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Facilitador'),
            preserve_default=False,
        ),
    ]
