# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_centro_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitador',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
