# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_personas_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='requisito',
            field=models.FileField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
