# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20171020_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='requisito',
            field=models.FileField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
