# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_auto_20171026_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='requisito',
        ),
    ]
