# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_auto_20171106_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='tipo_persona',
        ),
    ]
