# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_auto_20171106_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('ocupacion', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, max_length=100, null=True)),
                ('grado_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grado_Anterior', to='adminapp.GradoAnterior')),
                ('grupo_etnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.GrupoEtnico')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Municipio')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Sexo')),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_Persona', to='adminapp.TipoPersona')),
                ('trabaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trabaja', to='adminapp.Descicion')),
            ],
        ),
        migrations.AlterField(
            model_name='matricula',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Alumno'),
        ),
    ]
