# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_auto_20171106_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='fin_clases',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='inicio_clases',
        ),
        migrations.AddField(
            model_name='periodo',
            name='fin_clases',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='inicio_clases',
            field=models.DateField(blank=True, null=True),
        ),
    ]
