# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_auto_20171106_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentezco', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='tipo_persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='grado_anterior',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='grupo_etnico',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
        migrations.AddField(
            model_name='persona',
            name='familiar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to='adminapp.Alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='parentezco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Parentezco', to='adminapp.Parentezco'),
            preserve_default=False,
        ),
    ]
