# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='quien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
