# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_centro_quien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro',
            name='tipo_centro',
        ),
    ]
