# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_auto_20171113_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grado_anterior',
        ),
        migrations.AddField(
            model_name='matricula',
            name='condicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_anterior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Grado_Anterior', to='adminapp.GradoAnterior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
