# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_auto_20171114_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitador',
            name='correo',
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Centro', to='adminapp.Centro'),
        ),
    ]
