# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_auto_20171115_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitador',
            old_name='formacion_academida',
            new_name='formacion_academica',
        ),
    ]
