# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_auto_20171115_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='facilitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Facilitador'),
        ),
    ]
