# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_auto_20171116_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='centro',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Centro'),
            preserve_default=False,
        ),
    ]
