# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-16 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_grado_centro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.IntegerField()),
                ('inicio_clases', models.DateField(blank=True, null=True)),
                ('fin_clases', models.DateField(blank=True, null=True)),
                ('centro', models.ManyToManyField(to='adminapp.Centro')),
            ],
        ),
        migrations.CreateModel(
            name='Metodologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='fin_clases',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='inicio_clases',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Metodologia'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Periodo'),
        ),
    ]
