# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_auto_20171116_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='nombre_promotor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centro',
            name='promotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.Descicion'),
        ),
    ]
