from django.conf.urls import (url, handler400, handler403, handler404, handler500 )
from . import views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^$', views.index, name='index_admin'),
	# CENTROS
	url(r'^centros/depto/$', views.centrosxdepto, name='centrosxdepto'),
	url(r'^centros/(?P<pk>\d+)/$', views.all_centros_admin, name='all_centros_admin'),
	url(r'^centros/new/$', views.new_centro, name='new_centro'),
	url(r'^centros/new/add/$', views.new_centro_add, name='new_centro_add'),
	url(r'^centros/delete/(?P<pk>\d+)/$', views.delete_centro, name='delete_centro'),
	url(r'^centros/facilitador/(?P<pk>\d+)/$', views.facilitadorxcentro, name='facilitadorxcentro'),
	url(r'^facilitador/grados/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.gradosxfacilitador, name='gradosxfacilitador'),
	url(r'^facilitador/alumnos/(?P<pk>\d+)/$', views.alumnos, name='alumnos'),
	url(r'^facilitador/nuevo/(?P<pk>\d+)/$', views.nuevo_faci, name='nuevo_faci'),
	url(r'^facilitador/nuevo/add/$', views.nuevo_faci_add, name='nuevo_facil_add'),
	url(r'^facilitador/delete/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.delete_faci, name='delete_faci'),
	url(r'^alumnos/new/$', views.alumnonuevo, name='alumnonuevo'),
	url(r'^alumnos/new/add/$', views.alumnonuevo_add, name='alumnonuevo_add'),
	url(r'^alumnos/familiar/(?P<pk>\d+)/all/$', views.familiarxalumno, name='familiarxalumno'),
	url(r'^alumnos/familiar/(?P<pk>\d+)/$', views.nuevo_familiar, name='nuevo_familiar'),
	url(r'^alumnos/familiar/add/$', views.familiar_add, name='familiar_add'),
	url(r'^alumnos/familiar/delete/(?P<pk>\d+)/$', views.delete_familiar, name='delete_familiar'),
	url(r'^alumnos/$', views.alumnossinmat, name='alumnossinmat'),
	url(r'^alumnos/delete/(?P<pk>\d+)/$', views.delete_alumno, name='delete_alumno'),
	url(r'^alumnos/matricular/(?P<pk>\d+)/$', views.matricular_alumno, name='matricular_alumno'),
	url(r'^alumnos/matricular/add/$', views.matricular_alumno_add, name='matricular_alumno_add'),
	url(r'^perfil/$', views.perfil, name='perfil'),
	url(r'^configuracion/$', views.configuracion, name='config'),
	url(r'^configuracion/add/$', views.configuracion_add, name='config_add'),
	url(r'^matricula/nueva/(?P<pk>\d+)/$', views.matricular, name='matricular'),
	url(r'^matricula/nueva/add/$', views.matricular_add, name='matricular_add'),
	url(r'^grados/nuevo/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.nuevo_grado, name='nuevo_grado'),
	url(r'^grados/nuevo/add/$', views.nuevo_grado_add, name='nuevo_grado_add'),
	url(r'^grados/delete/(?P<pk>\d+)/$', views.delete_grado, name='delete_grado'),
	url(r'^certificados/$', views.certificados, name='certificados'),
	url(r'^certificados/estudio/$', views.certificados_estudio, name='certificados_estudio'),
	url(r'^certificados/conducta/$', views.certificados_conducta, name='certificados_conducta'),
	url(r'^certificados/himno/$', views.certificados_himno, name='certificados_himno'),
	url(r'^graficos/$', views.graficos, name='graficos'),

	# EDITAR
	url(r'^perfil/editar/(?P<pk>\d+)/$', views.editar_perfil ,name="editar_perfil"),
	url(r'^perfil/editar/add/$', views.editar_perfil_add ,name="editar_perfil_add"),
	url(r'^centros/editar/(?P<pk>\d+)/$', views.editar_centros ,name="editar_centros"),
	url(r'^centros/editar/add/$', views.editar_centros_add ,name="editar_centros_add"),
	url(r'^facilitador/editar/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.editar_faci ,name="editar_faci"),
	url(r'^facilitador/editar/add/$', views.editar_faci_add ,name="editar_faci_add"),
	url(r'^alumno/editar/(?P<pk>\d+)/$', views.editar_alumno ,name="editar_alumno"),
	url(r'^alumno/editar/add/$', views.editar_alumno_add ,name="editar_alumno_add"),
	url(r'^familiar/editar/(?P<pk>\d+)/$', views.editar_familiar ,name="editar_familiar"),
	url(r'^familiar/editar/add/$', views.editar_familiar_add ,name="editar_familiar_add"),

]